version: '3'
services:
  my-app:
    build: .
    image: mostafataha12/my-app:latest
    ports:
    - 3000:3000
    depends_on:
      - "db-init"
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
 
  db-init:
    build:
      context: ./utility-app
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"

volumes:
  mongo-data:
    driver: local
